import type { CaseStudy } from "./types";

/**
 * Reviewed production case studies, grouped by category.
 * Customer and project names may be public. Replace people, real network values,
 * internal domains, accounts, hosts and configuration values before publishing.
 */
export const caseStudyCategories = [
  "Cloud Migration",
  "Network and Traffic Flow",
  "Load Balancer and WAF",
  "VPN and Hybrid Connectivity",
  "Middleware and Enterprise Systems",
  "Production Troubleshooting",
] as const;

export const caseStudies: CaseStudy[] = [
  {
    slug: "idc-to-cloud-migration",
    category: "Cloud Migration",
    title: "IDC workloads migrated to a public cloud environment",
    status: "Case Study",
    context:
      "Customer A operated application and middleware servers in an IDC and moved selected workloads to a public cloud environment (AWS / NCP) while the IDC stayed in service during transition.",
    role: "Infrastructure engineer responsible for network and platform design, cutover execution and post-migration verification.",
    constraints: [
      "Existing IDC systems had to keep serving traffic during the transition.",
      "Change windows were fixed and approvals were required per change.",
      "Address ranges had to stay non-overlapping with existing private ranges (example: 192.0.2.0/24).",
    ],
    keyActions: [
      "Mapped inbound and outbound dependencies per system before any move.",
      "Designed VPC, subnet and routing layout and the path between IDC and cloud.",
      "Prepared rollback steps for each cutover step, not only for the whole cutover.",
      "Verified traffic paths after cutover with curl, DNS resolution checks, routing tables and packet capture.",
    ],
    result:
      "I verified that the migrated workloads served requests from the cloud, checked the traffic paths and documented the rollback procedure.",
    technologies: ["AWS", "NCP", "VPC", "Routing", "DNS", "Linux"],
    areas: ["cloud-infrastructure", "network-connectivity"],
  },
  {
    slug: "traffic-path-analysis",
    category: "Network and Traffic Flow",
    title: "End-to-end traffic path analysis across multiple systems",
    status: "Case Study",
    context:
      "Requests crossed client, load balancer, WAF, web tier, middleware and backend systems; symptoms appeared at the application while the cause was elsewhere on the path.",
    role: "Owned the traffic-path investigation across components owned by different teams.",
    constraints: [
      "Components were operated by different teams with different log formats and retention.",
      "Packet capture was permitted only on specific hosts and time windows.",
    ],
    keyActions: [
      "Reconstructed the request path hop by hop and stated the expected behaviour of each hop first.",
      "Correlated tcpdump captures, curl probes, routing tables and application logs against the same request window.",
      "Narrowed the fault domain to one component before proposing a change.",
    ],
    result:
      "I identified the failing hop from packet captures and logs and shared the findings and supporting data with the responsible team.",
    technologies: ["tcpdump", "curl", "Routing", "Linux", "Log analysis"],
    areas: ["network-connectivity", "cloud-infrastructure"],
  },
  {
    slug: "waf-load-balancer-behaviour",
    category: "Load Balancer and WAF",
    title: "Load balancer and WAF behaviour during request failures",
    status: "Case Study",
    context:
      "Intermittent request failures were reported for a service published through a load balancer with a WAF in front of it.",
    role: "Analysed load balancer and WAF behaviour and validated health-check and inspection assumptions.",
    constraints: [
      "WAF rules were shared across services, so changes affected more than the reported service.",
      "Reproduction depended on specific request shapes rather than volume.",
    ],
    keyActions: [
      "Compared load balancer target health state against backend readiness at the same timestamps.",
      "Distinguished responses generated by the WAF from responses generated by the backend.",
      "Reproduced failing requests with controlled curl requests including headers and method variations.",
    ],
    result:
      "Failure responses were attributed to a specific layer on the path, which made the corrective change reviewable by its owner.",
    technologies: ["Load Balancer", "WAF", "curl", "TLS", "HTTP"],
    areas: ["network-connectivity", "security-access"],
  },
  {
    slug: "vpn-hybrid-connectivity",
    category: "VPN and Hybrid Connectivity",
    title: "VPN and hybrid connectivity between on-premises and cloud",
    status: "Case Study",
    context:
      "On-premises networks and a cloud environment were connected over VPN so that migrated and non-migrated systems could keep communicating.",
    role: "Designed and validated the connectivity path and investigated reachability failures.",
    constraints: [
      "Address ranges on both sides had to remain non-overlapping (example: 192.0.2.0/24 and 198.51.100.0/24).",
      "Firewall policies on the on-premises side were managed by another team.",
    ],
    keyActions: [
      "Documented required flows as source, destination, port and direction before requesting policy changes.",
      "Verified tunnel state, route propagation and security policy separately instead of treating reachability as one condition.",
      "Confirmed both directions of each flow explicitly.",
    ],
    result:
      "Required flows were reachable with each layer verified independently, and the flow inventory served as the reference for later policy requests.",
    technologies: ["VPN", "Routing", "Firewall policy", "VPC"],
    areas: ["network-connectivity", "cloud-infrastructure", "security-access"],
  },
  {
    slug: "enterprise-middleware-operations",
    category: "Middleware and Enterprise Systems",
    title: "Enterprise middleware and UNIX production operations",
    status: "Case Study",
    context:
      "Production services ran on Linux and AIX with JEUS application servers and WebtoB web servers under change control.",
    role: "Operated middleware and OS layers, handled incidents and executed reviewed changes.",
    constraints: [
      "Changes required approval and a defined rollback path.",
      "Legacy components limited the range of acceptable configuration changes.",
    ],
    keyActions: [
      "Traced request handling from the web tier through the application server to the backend.",
      "Used middleware and system logs to separate resource exhaustion from application errors.",
      "Executed changes with pre-checks and post-checks defined in advance.",
    ],
    result:
      "Incidents were resolved with the responsible layer identified, and changes were applied within approved windows with verification steps recorded.",
    technologies: ["Linux", "AIX", "JEUS", "WebtoB", "Shell"],
    areas: ["cloud-infrastructure", "automation-iac"],
  },
  {
    slug: "production-troubleshooting-method",
    category: "Production Troubleshooting",
    title: "A repeatable method for production failure analysis",
    status: "Case Study",
    context:
      "Incidents arrived as user-visible symptoms with no indication of which component was at fault.",
    role: "Led analysis and communicated findings to application, network and security owners.",
    constraints: [
      "Time pressure during incidents, with restoration and root-cause work competing.",
      "Evidence had to be collected without changing the failing environment further.",
    ],
    keyActions: [
      "Established the actual request path and the last known-good hop before changing anything.",
      "Collected evidence per hop: packet captures, load balancer state, routing, DNS resolution and logs.",
      "Separated restoration actions from root-cause actions and recorded both.",
    ],
    result:
      "I used the collected evidence to agree on the failure scope and follow-up actions with the responsible teams.",
    technologies: ["tcpdump", "curl", "Routing", "Log analysis", "Linux"],
    areas: ["network-connectivity", "observability"],
  },
];

export function getCaseStudy(slug: string) {
  return caseStudies.find((c) => c.slug === slug);
}
